# Generated by Django 5.2.1 on 2025-05-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('member_count', models.IntegerField()),
                ('ticket_count', models.IntegerField()),
                ('tasks_to_do_count', models.IntegerField()),
                ('tasks_high_prio_count', models.IntegerField()),
                ('owner_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=600)),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('assignee_id', models.IntegerField()),
                ('reviewer', models.IntegerField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comments_count', models.IntegerField()),
            ],
        ),
    ]
