# Generated by Django 5.2.1 on 2025-05-26 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0002_alter_boards_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boarduser',
            options={'verbose_name': 'BoardUser', 'verbose_name_plural': 'BoardUser'},
        ),
    ]
