# Generated by Django 5.2.1 on 2025-06-02 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanmind_app', '0007_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='comments_count',
        ),
    ]
